version: "3"

services:

  db:
    image: postgres:9.6-alpine
    volumes:
      - analytics:/var/lib/postgresql/data/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=analytics
      - POSTGRES_PASSWORD=analytics
    networks:
      - database_network

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - net_api
      - database_network
    ports:
      - 8086:8080
    env_file: .env
    depends_on:
      - db

networks:
  net_api:
  database_network:
volumes:
  analytics:


